# agents/plan_synthesizer.py
from dataclasses import dataclass
from typing import Dict, Any, List, Optional
import datetime

@dataclass
class Leg:
    kind: str     # "short_call", "long_call", "short_put", "long_put"
    strike: float
    qty: int
    expiry: str   # e.g. "2025-11-01"

@dataclass
class Plan:
    symbol: str
    strategy: str
    dte: int
    notes: str
    legs: List[Leg]
    est_credit: Optional[float] = None
    est_debit: Optional[float] = None
    max_profit: Optional[float] = None
    max_loss: Optional[float] = None
    risk_level: str = "moderate"
    created_at: str = ""

def build_plan(symbol: str, strategy: str, params: Dict[str, Any]) -> Plan:
    # simple defaults
    dte = int(params.get("dte", 7))
    wings = int(params.get("wings", 5))
    risk_level = params.get("risk_level", "moderate")
    
    # Calculate expiry date
    expiry_date = datetime.datetime.now() + datetime.timedelta(days=dte)
    expiry_str = expiry_date.strftime("%Y-%m-%d")
    
    created_at = datetime.datetime.now().isoformat()
    
    # Mock current price - in real implementation, fetch from market data
    mock_prices = {
        "SPY": 450.0,
        "QQQ": 380.0,
        "AAPL": 175.0,
        "MSFT": 420.0,
        "TSLA": 250.0,
        "NVDA": 500.0
    }
    center = mock_prices.get(symbol, 100.0)
    
    notes = f"Draft plan generated by plan_synthesizer at {created_at} (no orders placed)."

    if strategy == "iron_condor":
        # Adjust wing size based on risk level
        if risk_level == "low":
            wings = max(wings, 10)
            strike_distance = 15
        elif risk_level == "high":
            wings = min(wings, 3)
            strike_distance = 8
        else:
            strike_distance = 10
            
        legs = [
            Leg("short_call", center + strike_distance, 1, expiry_str),
            Leg("long_call", center + strike_distance + wings, 1, expiry_str),
            Leg("short_put", center - strike_distance, 1, expiry_str),
            Leg("long_put", center - strike_distance - wings, 1, expiry_str),
        ]
        est_credit = wings * 0.3  # rough estimate
        max_profit = est_credit * 100
        max_loss = (wings - est_credit) * 100
        
        return Plan(
            symbol=symbol, 
            strategy=strategy, 
            dte=dte, 
            notes=notes, 
            legs=legs, 
            est_credit=est_credit,
            max_profit=max_profit,
            max_loss=max_loss,
            risk_level=risk_level,
            created_at=created_at
        )

    if strategy == "put_credit_spread":
        # Adjust based on risk level
        if risk_level == "low":
            wings = max(wings, 8)
            strike_distance = 10
        elif risk_level == "high":
            wings = min(wings, 3)
            strike_distance = 5
        else:
            strike_distance = 7
            
        legs = [
            Leg("short_put", center - strike_distance, 1, expiry_str),
            Leg("long_put", center - strike_distance - wings, 1, expiry_str),
        ]
        est_credit = wings * 0.2
        max_profit = est_credit * 100
        max_loss = (wings - est_credit) * 100
        
        return Plan(
            symbol=symbol, 
            strategy=strategy, 
            dte=dte, 
            notes=notes, 
            legs=legs, 
            est_credit=est_credit,
            max_profit=max_profit,
            max_loss=max_loss,
            risk_level=risk_level,
            created_at=created_at
        )

    if strategy == "call_credit_spread":
        if risk_level == "low":
            wings = max(wings, 8)
            strike_distance = 10
        elif risk_level == "high":
            wings = min(wings, 3)
            strike_distance = 5
        else:
            strike_distance = 7
            
        legs = [
            Leg("short_call", center + strike_distance, 1, expiry_str),
            Leg("long_call", center + strike_distance + wings, 1, expiry_str),
        ]
        est_credit = wings * 0.2
        max_profit = est_credit * 100
        max_loss = (wings - est_credit) * 100
        
        return Plan(
            symbol=symbol, 
            strategy=strategy, 
            dte=dte, 
            notes=notes, 
            legs=legs, 
            est_credit=est_credit,
            max_profit=max_profit,
            max_loss=max_loss,
            risk_level=risk_level,
            created_at=created_at
        )

    if strategy == "covered_call":
        # assumes you own 100 shares; only propose the call leg
        strike_distance = 5 if risk_level == "high" else 10
        legs = [Leg("short_call", center + strike_distance, 1, expiry_str)]
        est_credit = 0.60
        max_profit = est_credit * 100
        max_loss = float('inf')  # Unlimited downside on stock
        
        return Plan(
            symbol=symbol, 
            strategy=strategy, 
            dte=dte, 
            notes=f"{notes} Assumes 100 shares of {symbol} owned.", 
            legs=legs, 
            est_credit=est_credit,
            max_profit=max_profit,
            max_loss=max_loss,
            risk_level=risk_level,
            created_at=created_at
        )
    
    if strategy == "protective_put":
        # assumes you own 100 shares; only propose the put leg
        strike_distance = 5 if risk_level == "high" else 15
        legs = [Leg("long_put", center - strike_distance, 1, expiry_str)]
        est_debit = 1.50
        max_profit = float('inf')  # Unlimited upside on stock
        max_loss = strike_distance * 100 + est_debit * 100
        
        return Plan(
            symbol=symbol, 
            strategy=strategy, 
            dte=dte, 
            notes=f"{notes} Assumes 100 shares of {symbol} owned.", 
            legs=legs, 
            est_debit=est_debit,
            max_profit=max_profit,
            max_loss=max_loss,
            risk_level=risk_level,
            created_at=created_at
        )
    
    if strategy == "long_straddle":
        legs = [
            Leg("long_call", center, 1, expiry_str),
            Leg("long_put", center, 1, expiry_str),
        ]
        est_debit = 8.0 if risk_level == "high" else 5.0
        max_profit = float('inf')  # Unlimited
        max_loss = est_debit * 100
        
        return Plan(
            symbol=symbol, 
            strategy=strategy, 
            dte=dte, 
            notes=notes, 
            legs=legs, 
            est_debit=est_debit,
            max_profit=max_profit,
            max_loss=max_loss,
            risk_level=risk_level,
            created_at=created_at
        )

    raise ValueError(f"Unsupported strategy: {strategy}")